---
#- hosts: k8s_cluster:etcd
- hosts: vagrant_nodes
  gather_facts: false
  pre_tasks:
    - name: Create local ansible tmp dir
      delegate_to: localhost
      connection: local
      run_once: True
      become: False
      file:
        state: directory
        path: "{{ playbook_dir }}/tmp/"

    - set_fact:
        ansible_ssh_private_key_file: "{{ playbook_dir }}/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
        artifacts_dir: "{{ playbook_dir }}/tmp/artifacts/"

    - name: ensure connectivity
      raw: uptime


- import_playbook: external/kubespray_senorsmile/cluster.yml
